/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Formularios;

import clases.*;
import java.sql.*;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author JoseFrancisco
 */
public class JDcursos extends javax.swing.JDialog {

    /**
     * Creates new form JDcursos
     */
    public JDcursos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidcurso = new javax.swing.JTextField();
        txtcurso = new javax.swing.JTextField();
        cmdbuscar = new javax.swing.JButton();
        cmdagregar = new javax.swing.JButton();
        cmdeditar = new javax.swing.JButton();
        cmdeliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("ADMINISTRAR CURSO");

        jLabel2.setText("ID curso");

        jLabel3.setText("Curso");

        cmdbuscar.setText("Buscar");
        cmdbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdbuscarActionPerformed(evt);
            }
        });

        cmdagregar.setText("Agregar");
        cmdagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdagregarActionPerformed(evt);
            }
        });

        cmdeditar.setText("Editar");
        cmdeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeditarActionPerformed(evt);
            }
        });

        cmdeliminar.setText("Eliminar");
        cmdeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdeliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdagregar)
                        .addGap(44, 44, 44)
                        .addComponent(cmdeditar)
                        .addGap(36, 36, 36)
                        .addComponent(cmdeliminar)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(txtcurso))
                                .addGap(106, 106, 106))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtidcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmdbuscar)
                                .addGap(46, 46, 46))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtidcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdbuscar))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdagregar)
                    .addComponent(cmdeditar)
                    .addComponent(cmdeliminar))
                .addGap(0, 86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdbuscarActionPerformed
           Conexion basedatos = new Conexion();
        basedatos.conectar();
        Connection con;
        con = basedatos.getConexion();
        ResultSet consulta;
       
        try
        {
         Statement comando  = con.createStatement();      
        consulta = comando.executeQuery("select curso where idcurso = '"+txtidcurso.getText()+"'");
         if(consulta.next())
	{
	txtcurso.setText(consulta.getString("curso"));
	
	}
         else
             JOptionPane.showMessageDialog(this, "REGISTRO no existente");
      con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "ERROR 300"+e);
        }
    }//GEN-LAST:event_cmdbuscarActionPerformed

    private void cmdagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdagregarActionPerformed
             Conexion basedatos = new Conexion();
     Connection conn;
     basedatos.conectar();
     try
     {
         conn = basedatos.getConexion();
         Statement comando = conn.createStatement();
         comando.executeUpdate("insert into cursos () values(null,'"+txtcurso.getText()+"')");
         JOptionPane.showMessageDialog(this, "CURSO AGREGADO correctamente");
         conn.close();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(this, "Erro 100: "+ e);
     }
    }//GEN-LAST:event_cmdagregarActionPerformed

    private void cmdeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeditarActionPerformed
               Conexion basedatos = new Conexion();
     Connection conn;
     basedatos.conectar();
     try
     {
         conn = basedatos.getConexion();
         Statement comando = conn.createStatement();
         comando.executeUpdate("Update cursos='"+txtcurso.getText()+"' where idcurso ='"+txtidcurso.getText()+"'");
         JOptionPane.showMessageDialog(this, "Registro  EDITADO correctamente");
         conn.close();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(this, "Erro 400: "+ e);
     }
    }//GEN-LAST:event_cmdeditarActionPerformed

    private void cmdeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdeliminarActionPerformed
                Conexion basedatos = new Conexion();
     Connection conn;
     basedatos.conectar();
     try
     {
         conn = basedatos.getConexion();
         Statement comando = conn.createStatement();
         comando.executeUpdate("delete from CURSO where idcurso ='"+txtidcurso.getText()+"'");
         JOptionPane.showMessageDialog(this, "CURSO ELIMINADO correctamente");
         txtidcurso.setText("");
         txtcurso.setText("");
         conn.close();
     }
     catch(Exception e)
     {
         JOptionPane.showMessageDialog(this, "Erro 400: "+ e);
     }
    }//GEN-LAST:event_cmdeliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDcursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDcursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDcursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDcursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDcursos dialog = new JDcursos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdagregar;
    private javax.swing.JButton cmdbuscar;
    private javax.swing.JButton cmdeditar;
    private javax.swing.JButton cmdeliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtcurso;
    private javax.swing.JTextField txtidcurso;
    // End of variables declaration//GEN-END:variables
}
